# # Remote Setting
# baseurl: "/guidelines"
# # url: ""

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# plugins:
#   - jekyll-latex

markdown: kramdown
kramdown:
  mathjs

